# Generated by Django 4.1.1 on 2022-10-02 02:58

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('todo', '0005_listitem_item_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTodoTemplate',
            new_name='Template',
        ),
    ]
