# Generated by Django 4.1 on 2022-10-05 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_rename_usertodotemplate_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.user'),
        ),
    ]
