# Generated by Django 4.1.1 on 2022-10-04 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0006_account"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Account",
        ),
    ]
