# Generated by Django 4.1.1 on 2022-11-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_list_user_id_alter_template_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='list_tag',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
