# Generated by Django 4.1.3 on 2022-11-19 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0010_listtags"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shared_user", models.CharField(max_length=200)),
                (
                    "list_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="todo.list"
                    ),
                ),
            ],
        ),
    ]
