# Generated by Django 4.1.3 on 2022-11-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0012_sharedlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="is_shared",
            field=models.BooleanField(default=False),
        ),
    ]
